// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMCInc2oXPLf8Kw1IS4nk3ZgdRy-6bM9I',
    appId: '1:835269606922:web:a24b46713e335c0f4de9f3',
    messagingSenderId: '835269606922',
    projectId: 'the-last-wish-e71dc',
    authDomain: 'the-last-wish-e71dc.firebaseapp.com',
    storageBucket: 'the-last-wish-e71dc.firebasestorage.app',
    measurementId: 'G-KWN78F5FYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO8IXGE2Iuq2omVdJWy3YkTcr373yzCLY',
    appId: '1:835269606922:android:329b63022685ec7e4de9f3',
    messagingSenderId: '835269606922',
    projectId: 'the-last-wish-e71dc',
    storageBucket: 'the-last-wish-e71dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXjiPfVVZcIags5xgb-Kg1qcdmcpLteX4',
    appId: '1:835269606922:ios:3a1211bcbc1976b84de9f3',
    messagingSenderId: '835269606922',
    projectId: 'the-last-wish-e71dc',
    storageBucket: 'the-last-wish-e71dc.firebasestorage.app',
    iosBundleId: 'com.example.theLastWish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXjiPfVVZcIags5xgb-Kg1qcdmcpLteX4',
    appId: '1:835269606922:ios:3a1211bcbc1976b84de9f3',
    messagingSenderId: '835269606922',
    projectId: 'the-last-wish-e71dc',
    storageBucket: 'the-last-wish-e71dc.firebasestorage.app',
    iosBundleId: 'com.example.theLastWish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMCInc2oXPLf8Kw1IS4nk3ZgdRy-6bM9I',
    appId: '1:835269606922:web:8580986e9de707f04de9f3',
    messagingSenderId: '835269606922',
    projectId: 'the-last-wish-e71dc',
    authDomain: 'the-last-wish-e71dc.firebaseapp.com',
    storageBucket: 'the-last-wish-e71dc.firebasestorage.app',
    measurementId: 'G-2187JM06P6',
  );
}
